### PR TITLE
Add vcf-js parser to benchmark

### PR DESCRIPTION
**Pull request by cmdcolin**
This just was a little demo to try to test out our vcf-js parsing module

The vcf-js parser lazily parses the genotypes so that is probably a nice advantage for it, and it requires some manual setup to do the parsing using streams which isnt built into the module but seems to at least show up on the chart (nodejs streams dont always look like the prettiest code but can be fast)

Welcome to run the test on your own machine also, short readme provided to demo

### CODE REVIEW

**Comment by brentp** [comment]
Thanks! Two requests:
1. Don't update the README, I'll do that so at least everything is run on the same machine.
2. append to an Array and then get the mean from the list. It doesn't affect the timings, but now that all the other implementations must follow that silly precedent, we should stick to it.

cheers!

**Comment by cmdcolin** [comment]
sure thing. README changes removed, and uses an append to array now

**Comment by cmdcolin** [comment]
updated slightly to use a native node module "readline" instead of pump/split2 also, bit faster

**Comment by brentp** [comment]
thanks!
for best of 3 tries, I get:
```
$ time node js-vcf-js/index.js 1kg.chr1.subset.vcf.gz 
5992.641098163443

real	0m29.323s
user	0m32.638s
sys	0m2.431s

```
does that match what you expect? I have node v10.19.0 and don't do a lot of js stuff so want to make sure it's fair.

**Comment by cmdcolin** [comment]
I get approx the same on node 10 but it is actually considerably faster with newer versions of node. on node 16, on my machine almost 10 seconds faster (can use nvm to install multiple versions)

```
~$ nvm install 16
...
~$ nvm use 16
Now using node v16.13.0 (npm v8.1.0)
~$ node
~$ yarn  
...
~$ time node index.js ../1kg.chr1.subset.vcf.gz 
5992.641098163443
node index.js ../1kg.chr1.subset.vcf.gz  17.67s user 2.27s system 118% cpu 16.866 total

~$ nvm install 10.19.0 
...
~$ nvm use 10.19.0
Now using node v10.19.0 (npm v6.13.4)
~$ yarn
...
~$ time node index.js ../1kg.chr1.subset.vcf.gz
5992.641098163443
node index.js ../1kg.chr1.subset.vcf.gz  27.25s user 2.37s system 118% cpu 25.034 total
```

**Comment by brentp** [comment]
thanks! added it with v16 timings. the difference is not as large on my machine, but it gets it down to ~24s so much better than the 32s.

**Comment by cmdcolin** [comment]
cool, not bad! I was expecting to be quite slow going into this so cool to see even to be this fast

**Pull request merged**
